version: '3'
services:
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5001:80"
    container_name: pgadmin
    #volumes:
      #- pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped

  postgres:
    #build:
     # dockerfile: Dockerfile
      #context: 
    image: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5002:5432"
    container_name: postgres
    restart: unless-stopped











